### ISSUE TITLE
How do you like Typesaurus?

### ISSUE THREAD

**Issue by kossnocorp** [camr/staff-map#1]
Hey, I'm the author of Typesaurus, and I noticed that you've used it in the project. How do you like it, do you have any feedback? Thanks!

**Comment by camr** [comment]
Hi @kossnocorp, I'm actually very impressed with Typesaurus. I'm not doing anything crazy with firestore, but being able to easily wrap the functionality with types is really nice.

The only pain point I found was being surprised at the lack of initialization/configuration. It wasn't immediately clear to me that Typesaurus didn't need anything more that the underlying firebase initialization. Pretty cool once I realized that, though.

I was really impressed with docs and examples for each function. Great job on those! And by the fact that the library didn't interfere with any of the vuex Typescript libraries I'm using. Usually I just assume there will be some sort of conflict to work around.

So, yeah. Very cool project, thanks for making and open sourcing it! I hope to have more reasons to use it in the future.

**Comment by kossnocorp** [comment]
Amazing, I'm glad to hear that you like it!

> The only pain point I found was being surprised at the lack of initialization/configuration. It wasn't immediately clear to me that Typesaurus didn't need anything more that the underlying firebase initialization. Pretty cool once I realized that, though.

That's a good point! I'll add a note to [the get started section](https://github.com/kossnocorp/typesaurus#get-started) about that.

Thank you for your answer, appreciate it!

**Comment by kossnocorp** [comment]
Btw, I'm looking for developers' testimonials for the README & website. I would appreciate if you can write one :-3
